services:
  - type: web
    name: yowyob-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: "-Xmx384m -Xms256m -Djava.security.egd=file:/dev/./urandom"
      - key: DB_URL
        fromDatabase:
          name: yowyob-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: yowyob-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: yowyob-db
          property: password
          
    healthCheckPath: /actuator/health
    autoDeploy: true
    numInstances: 1

databases:
  - name: yowyob-db
    databaseName: yowyob
    user: yowyob_user
    plan: free
    region: frankfurt